apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-system
  labels:
    app: kube-bench
spec:
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      containers:
        - name: kube-bench
          image: aquasec/kube-bench:latest
          args:
            - "--benchmark"
            - "cis-1.23" # Update to match your cluster version
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
            - name: etc-systemd
              mountPath: /etc/systemd
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: etc-systemd
          hostPath:
            path: /etc/systemd
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
  backoffLimit: 3
